CREATE DATABASE IF NOT EXISTS `cine` /*!40100 DEFAULT CHARACTER SET latin1 */
CREATE TABLE `salas` (
  `nroSala` int(11) NOT NULL,
  PRIMARY KEY (`nroSala`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

